// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oracle/cluster-api-provider-oci/cloud/scope (interfaces: NpnWorkloadClientInterface)

// Package scope is a generated GoMock package.
package scope

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockNpnWorkloadClientInterface is a mock of NpnWorkloadClientInterface interface.
type MockNpnWorkloadClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNpnWorkloadClientInterfaceMockRecorder
}

// MockNpnWorkloadClientInterfaceMockRecorder is the mock recorder for MockNpnWorkloadClientInterface.
type MockNpnWorkloadClientInterfaceMockRecorder struct {
	mock *MockNpnWorkloadClientInterface
}

// NewMockNpnWorkloadClientInterface creates a new mock instance.
func NewMockNpnWorkloadClientInterface(ctrl *gomock.Controller) *MockNpnWorkloadClientInterface {
	mock := &MockNpnWorkloadClientInterface{ctrl: ctrl}
	mock.recorder = &MockNpnWorkloadClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNpnWorkloadClientInterface) EXPECT() *MockNpnWorkloadClientInterfaceMockRecorder {
	return m.recorder
}

// DeleteNpn mocks base method.
func (m *MockNpnWorkloadClientInterface) DeleteNpn(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNpn", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNpn indicates an expected call of DeleteNpn.
func (mr *MockNpnWorkloadClientInterfaceMockRecorder) DeleteNpn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNpn", reflect.TypeOf((*MockNpnWorkloadClientInterface)(nil).DeleteNpn), arg0)
}

// GetOrCreateNpn mocks base method.
func (m *MockNpnWorkloadClientInterface) GetOrCreateNpn(arg0 context.Context) (*unstructured.Unstructured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateNpn", arg0)
	ret0, _ := ret[0].(*unstructured.Unstructured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateNpn indicates an expected call of GetOrCreateNpn.
func (mr *MockNpnWorkloadClientInterfaceMockRecorder) GetOrCreateNpn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateNpn", reflect.TypeOf((*MockNpnWorkloadClientInterface)(nil).GetOrCreateNpn), arg0)
}

// HasNpnCrd mocks base method.
func (m *MockNpnWorkloadClientInterface) HasNpnCrd(arg0 context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNpnCrd", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNpnCrd indicates an expected call of HasNpnCrd.
func (mr *MockNpnWorkloadClientInterfaceMockRecorder) HasNpnCrd(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNpnCrd", reflect.TypeOf((*MockNpnWorkloadClientInterface)(nil).HasNpnCrd), arg0)
}

// NewWorkloadClient mocks base method.
func (m *MockNpnWorkloadClientInterface) NewWorkloadClient(arg0 context.Context) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWorkloadClient", arg0)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewWorkloadClient indicates an expected call of NewWorkloadClient.
func (mr *MockNpnWorkloadClientInterfaceMockRecorder) NewWorkloadClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWorkloadClient", reflect.TypeOf((*MockNpnWorkloadClientInterface)(nil).NewWorkloadClient), arg0)
}
